class_name TableLayout
extends RefCounted
## The machine, as data.
##
## Every wall, target and lane on the playfield is described here as plain
## numbers, and `table.gd` turns that description into collision shapes while
## `table_art.gd` draws the same numbers. Nothing is hand-placed in a .tscn.
##
## That is not tidiness for its own sake. Table mods are a core roguelike axis
## of this game ("Extra Bumper", "Wide Flippers", "Post Rubber", "Outlane
## Guards"), and a mod is only cheap to build if the playfield is a value that
## can be edited before it is instantiated. A scene full of hand-placed nodes
## would make every mod a bespoke patch. It also means collision and rendering
## cannot drift apart, because there is only one source for both.
##
## Coordinates are table-local pixels: origin at the top-left of the playfield,
## +x right, +y down. The table node is positioned in the viewport by `game.gd`.

# --- Overall dimensions -------------------------------------------------------

const WIDTH := 280.0
const HEIGHT := 344.0

const WALL_THICKNESS := 6.0
const BALL_RADIUS := 4.0

## The lower playfield is bounded by the left wall and the plunger-lane divider,
## not by the outer edge of the cabinet — so its centre sits left of the arch's
## centre. Real machines do exactly this; the plunger lane eats the right side
## below the arch and the flippers straddle what is left.
const PLAYFIELD_LEFT := 6.0
const PLAYFIELD_RIGHT := 248.0
const LOWER_CENTRE := (PLAYFIELD_LEFT + PLAYFIELD_RIGHT) * 0.5  # 127.0

# --- Top arch -----------------------------------------------------------------

const ARCH_CENTRE := Vector2(140.0, 72.0)
const ARCH_RX := 134.0
const ARCH_RY := 62.0

# --- Plunger lane -------------------------------------------------------------

const LANE_DIVIDER_X := 251.0  # wall centre; spans 248..254
const LANE_DIVIDER_TOP := 96.0
const LANE_FLOOR_Y := 332.0
const LANE_RIGHT_X := 274.0
const BALL_REST := Vector2(264.0, 320.0)

## One-way gate across the mouth of the plunger lane. Without it a ball that
## wanders back into the lane is a free save: it rolls down to the plunger and
## can simply be launched again, never draining and never losing its MULT.
##
## It slopes *up* to the right on purpose. A ball that arrives from the
## playfield lands on the gate and rolls back down its slope into the playfield
## instead of balancing on it, which is what stops the gate oscillating between
## open and closed underneath a stationary ball.
const GATE_A := Vector2(254.0, 92.0)
const GATE_B := Vector2(274.0, 84.0)
const GATE_SENSOR := Rect2(251.0, 62.0, 26.0, 28.0)
## Held closed for long enough that a ball resting on it has time to roll clear
## before it opens again.
const GATE_HOLD := 0.6

## Impulse speeds for a zero-charge and a full-charge plunge, in px/s.
##
## Anchored to the geometry rather than picked: lifting the ball from y=320 to
## the arch at y~48 against 480px/s^2 needs v = sqrt(2*480*272) ~= 511px/s. So
## MIN deliberately falls short (a weak plunge dies in the orbit and is a real
## outcome you can misplay) and MAX comfortably clears it.
const PLUNGE_MIN_SPEED := 400.0
const PLUNGE_MAX_SPEED := 640.0

# --- Flippers -----------------------------------------------------------------

const FLIPPER_LENGTH := 34.0
const FLIPPER_RADIUS := 4.5
const FLIPPER_SPAN := 39.0  # pivot offset either side of LOWER_CENTRE

const LEFT_FLIPPER_PIVOT := Vector2(LOWER_CENTRE - FLIPPER_SPAN, 300.0)   # (88, 300)
const RIGHT_FLIPPER_PIVOT := Vector2(LOWER_CENTRE + FLIPPER_SPAN, 300.0)  # (166, 300)

## Rest and flipped angles. Both flippers use a shape running along +x from the
## pivot; the right one is simply rotated past 180 degrees, which keeps one
## shape and one sweep routine for both instead of a mirrored special case.
const LEFT_REST_DEG := 28.0
const LEFT_UP_DEG := -30.0
const RIGHT_REST_DEG := 152.0
const RIGHT_UP_DEG := 210.0

## A 58-degree sweep in 48ms is roughly a real solenoid. Fast enough to feel
## instant, slow enough that the kinematic body still resolves contacts at
## 120Hz instead of teleporting through the ball.
const FLIPPER_SWEEP_TIME := 0.048

# --- Lanes --------------------------------------------------------------------

## The inlane floor: a wall the ball rolls down, right into the flipper root.
## The outlane is the channel underneath it, generated by offsetting this same
## polyline outward — which is what keeps it a constant width instead of a
## wedge that a ball can wander into anywhere along its length.
const OUTLANE_WIDTH := 18.0

## Stored as plain Arrays of Vector2 rather than PackedVector2Array, because
## GDScript will not accept a PackedVector2Array constructor in a `const` --
## only a literal is a constant expression. The accessors below pack them.
##
## The last point is the most load-bearing number on the table, because two
## things fight over it.
##
## The inlane wants to end *at* the flipper, so a ball rolling down it lands on
## the flipper rather than in the gap beside it. The outlane -- which is this
## same wall offset 18px outward -- wants to end well short of the flipper, so
## that its exit corridor, between the offset wall and the flipper's root
## circle, is wider than a ball. Both live in the span between this point and
## the pivot, and the geometry is fixed:
##
##   corridor = pivot.x - end.x - 1.9      (see offset_side and FLIPPER_RADIUS)
##
## so an 8px ball needs `pivot.x - end.x >= 10`. At pivot.x=88 that caps this
## point at x=78, and the cost is that the ball has ~12px of unsupported hop
## from the end of the inlane onto the flipper.
##
## A real machine does not have to choose: its outlane passes *under* the
## playfield behind the flipper. A 2D projection has no behind, so this is the
## honest compromise. Two earlier versions ended at (86,310) and (86,291) and
## both wedged the ball permanently against the flipper root -- the headless
## sim caught each as a table that scored well and never drained a ball.
const LEFT_INLANE_FLOOR := [
	Vector2(22, 240), Vector2(44, 268), Vector2(62, 280), Vector2(76, 286),
]

## Left orbit guide: makes a lane up the left side wide enough for one ball.
## It stops short of the inlane floor on purpose — the gap between the two is
## the outlane mouth, so a ball coming down the orbit either catches the inlane
## and lives or slips past it and drains. That gamble is the point of the orbit.
const LEFT_ORBIT_GUIDE := [
	Vector2(30, 96), Vector2(28, 150), Vector2(32, 200), Vector2(34, 232),
]

# --- Scoring elements ---------------------------------------------------------

const BUMPER_RADIUS := 12.0
const BUMPERS := [
	Vector2(100, 130),
	Vector2(154, 118),
	Vector2(127, 168),
]
## Where "Extra Bumper" (table mod) drops its fourth pop bumper.
const BUMPER_MOD_SLOT := Vector2(127, 100)

## The kicking face is called out separately from the triangle, because the
## kick direction is that face's normal and re-deriving it from the polygon's
## winding order is a bug waiting for someone to reorder a vertex.
## The bottom edge is the inlane's ceiling, so it has to clear the inlane floor
## by more than a ball diameter along its whole length.
const LEFT_SLINGSHOT_TRI := [Vector2(52, 212), Vector2(54, 256), Vector2(98, 244)]
const LEFT_SLINGSHOT_FACE := [Vector2(52, 212), Vector2(98, 244)]
const SLINGSHOT_KICK := 260.0

const TARGET_SIZE := Vector2(6, 16)
const DROP_TARGETS := [
	Vector2(52, 150),
	Vector2(52, 172),
	Vector2(52, 194),
]
const STANDUP_TARGETS := [
	Vector2(232, 140),
	Vector2(232, 168),
]

## Spinner sits in the left orbit lane, so the only way to score it is to make
## the orbit — it is the reward half of the orbit's risk.
const SPINNER_RECT := Rect2(9, 122, 18, 16)
const ROLLOVER_SIZE := Vector2(22, 10)
const ROLLOVERS := [
	Vector2(105, 56),
	Vector2(149, 56),
]
## Crossing this, high on the left orbit, completes an orbit shot.
const ORBIT_RECT := Rect2(9, 96, 18, 12)

## The drain line sits exactly at the bottom of the playfield, and the outlane
## chutes stop 6px below it. Both are bounded so that the whole table, chute
## tips included, fits inside the 640x360 viewport once the table is placed at
## its origin -- otherwise the drain is drawn off the bottom of the screen and
## the ball vanishes a moment before it is lost.
const DRAIN_Y := HEIGHT
const CHUTE_OVERRUN := 6.0


# --- Derived geometry ---------------------------------------------------------


## The top arch, as a polyline running left-to-right along its inside face.
static func arch_polyline(steps: int = 32) -> PackedVector2Array:
	var pts := PackedVector2Array()
	for i in steps + 1:
		var t: float = PI * (1.0 - float(i) / float(steps))
		pts.append(ARCH_CENTRE + Vector2(ARCH_RX * cos(t), -ARCH_RY * sin(t)))
	return pts


## Mirror a point across the lower playfield's centre line.
static func mirror(p: Vector2) -> Vector2:
	return Vector2(2.0 * LOWER_CENTRE - p.x, p.y)


static func mirror_all(pts: PackedVector2Array) -> PackedVector2Array:
	var out := PackedVector2Array()
	for p in pts:
		out.append(mirror(p))
	return out


## Offset a polyline sideways by a constant distance, keeping the two curves
## parallel. `side` is +1 for the left-hand normal, -1 for the right-hand one.
##
## Godot's Geometry2D.offset_polyline inflates a line into a closed ribbon,
## which is the wrong shape here: we want one displaced curve, not both sides
## joined at the ends.
static func offset_side(pts: PackedVector2Array, dist: float, side: float) -> PackedVector2Array:
	var n := pts.size()
	if n < 2:
		return pts
	var normals: Array[Vector2] = []
	for i in n - 1:
		var d := (pts[i + 1] - pts[i]).normalized()
		normals.append(Vector2(-d.y, d.x) * side)
	var out := PackedVector2Array()
	for i in n:
		# Interior vertices average the two adjacent segment normals so the
		# offset curve turns the corner without a notch.
		var nv: Vector2
		if i == 0:
			nv = normals[0]
		elif i == n - 1:
			nv = normals[n - 2]
		else:
			nv = (normals[i - 1] + normals[i]).normalized()
		out.append(pts[i] + nv * dist)
	return out


## The left inlane floor, with its upper end shifted along +x.
##
## That one point is how "The Drain" (boss: outlanes twice as wide) and
## "Outlane Guards" (mod: outlanes narrowed) are implemented. Both act on the
## *mouth* of the outlane -- the gap between the end of the orbit guide and the
## start of this wall -- rather than on the channel's width, because the
## channel is already only just wider than a ball and the cabinet edge is right
## there. How often a ball falls in is set at the mouth; the channel below it
## is a corridor either way.
static func inlane_floor(mouth_shift: float = 0.0) -> PackedVector2Array:
	var pts := PackedVector2Array(LEFT_INLANE_FLOOR)
	pts[0] = pts[0] + Vector2(mouth_shift, 0.0)
	return pts


## One slingshot, mirrored from the left one rather than written out twice --
## the two must stay symmetric, and two lists of coordinates do not.
static func slingshot(is_left: bool) -> Dictionary:
	var tri := PackedVector2Array(LEFT_SLINGSHOT_TRI)
	var a: Vector2 = LEFT_SLINGSHOT_FACE[0]
	var b: Vector2 = LEFT_SLINGSHOT_FACE[1]
	if not is_left:
		tri = mirror_all(tri)
		a = mirror(a)
		b = mirror(b)
	return {"tri": tri, "face_a": a, "face_b": b}


## The outer wall of an outlane, continued straight down past the drain line.
##
## Without that last segment the wall simply stops in mid-air, and because
## walls are stroked with round end caps, what it stops with is a dome — which
## a ball rolling down the outlane comes to rest on top of, balanced, forever.
## The headless sim found this as a table that scored well and never drained a
## ball. Extending the polyline moves the cap below the drain, so the tip is a
## chute instead of a perch.
static func _outlane_chute(inlane: PackedVector2Array, side: float) -> PackedVector2Array:
	var chute := offset_side(inlane, OUTLANE_WIDTH, side)
	chute.append(Vector2(chute[chute.size() - 1].x, DRAIN_Y + CHUTE_OVERRUN))
	return chute


## Every static wall on the table, as polylines to be stroked into collision.
static func walls(mouth_shift: float = 0.0) -> Array:
	var w: Array = []
	var left_inlane := inlane_floor(mouth_shift)

	w.append(arch_polyline())

	# Left cabinet wall, continuing into the outer wall of the left outlane and
	# then straight down past the drain line.
	var left_outer := PackedVector2Array([Vector2(6, 70), Vector2(6, 248)])
	left_outer.append_array(_outlane_chute(left_inlane, 1.0))
	w.append(left_outer)

	# Right cabinet wall and the plunger lane it encloses.
	w.append(PackedVector2Array([
		Vector2(LANE_RIGHT_X, 70), Vector2(LANE_RIGHT_X, LANE_FLOOR_Y),
		Vector2(LANE_DIVIDER_X, LANE_FLOOR_Y),
	]))
	w.append(PackedVector2Array([
		Vector2(LANE_DIVIDER_X, LANE_DIVIDER_TOP), Vector2(LANE_DIVIDER_X, LANE_FLOOR_Y),
	]))

	# Inlane floors, and the outer wall of the right outlane.
	w.append(left_inlane)
	var right_inlane := mirror_all(left_inlane)
	w.append(right_inlane)
	# Side flips for the mirrored wall: mirroring reverses the polyline's
	# handedness, so the same +1 normal that points outward on the left points
	# back into the playfield on the right.
	w.append(_outlane_chute(right_inlane, -1.0))

	# Orbit guides.
	var left_guide := PackedVector2Array(LEFT_ORBIT_GUIDE)
	w.append(left_guide)
	w.append(mirror_all(left_guide))

	return w


## The two outlane channels, as polygons. Used to tell an outlane drain from a
## centre drain, which Outlane Insurance pays out on.
static func outlane_polys(mouth_shift: float = 0.0) -> Array:
	var left := inlane_floor(mouth_shift)
	var out: Array = []
	for spec in [[left, 1.0], [mirror_all(left), -1.0]]:
		var inner: PackedVector2Array = spec[0]
		var outer: PackedVector2Array = offset_side(inner, OUTLANE_WIDTH, spec[1])
		var poly := PackedVector2Array()
		poly.append_array(inner)
		for i in range(outer.size() - 1, -1, -1):
			poly.append(outer[i])
		out.append(poly)
	return out


static func flipper_angles(is_left: bool) -> Vector2:
	## Returns (rest, flipped) in radians.
	if is_left:
		return Vector2(deg_to_rad(LEFT_REST_DEG), deg_to_rad(LEFT_UP_DEG))
	return Vector2(deg_to_rad(RIGHT_REST_DEG), deg_to_rad(RIGHT_UP_DEG))
